sudo: false
language: erlang
notifications:
  email:
    recipients: jpd.sousa@campus.fct.unl.pt
    on_success: never
    on_failure: always
otp_release:
  - 18.0
install:
  - pip install codecov
script:
  - make test
after_success:
  codecov
