sudo: false
language: erlang
notifications:
  email:
    recipients: jpd.sousa@campus.fct.unl.pt
    on_success: never
    on_failure: always
otp_release:
  - 18.0
before_install:
  - chmod +x dockerfiles/install_antidotedb.sh
install:
  - make compile
  - mkdir -p _build/test/logs
  - ./dockerfiles/install_antidotedb.sh
before_script:
  - cd antidote && make console &
  - sleep 10
script:
  - make test
  - make ct
after_success:
  - bin/covertool -cover _build/test/cover/eunit.coverdata -appname aql -output cobertura.xml
  - codecov
