INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (1, 'Harvard University', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (2, 'Stanford University', '2');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (3, 'University of California, Berkeley', '3');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (4, 'University of Cambridge', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (5, 'Massachusetts Institute of Technology (MIT)', '4');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (6, 'Princeton University', '5');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (7, 'University of Oxford', '2');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (8, 'California Institute of Technology', '6');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (9, 'Columbia University', '7');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (10, 'University of Chicago', '8');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (11, 'Yale University', '9');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (12, 'University of California, Los Angeles', '10');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (13, 'Cornell University', '11');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (14, 'University of California, San Diego', '12');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (15, 'University of Washington', '13');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (16, 'Johns Hopkins University', '14');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (17, 'University College London', '3');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (18, 'University of Pennsylvania', '15');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (19, 'Swiss Federal Institute of Technology Zurich', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (20, 'The University of Tokyo', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (21, 'University of California, San Francisco', '16');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (22, 'The Imperial College of Science, Technology and Medicine', '4');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (23, 'University of Michigan-Ann Arbor', '17');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (24, 'Washington University in St. Louis', '17');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (25, 'Duke University', '19');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (26, 'Northwestern University', '20');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (27, 'University of Toronto', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (28, 'University of Wisconsin - Madison', '21');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (29, 'New York University', '22');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (30, 'University of Copenhagen', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (31, 'University of Illinois at Urbana-Champaign', '23');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (32, 'Kyoto University', '2');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (33, 'University of Minnesota, Twin Cities', '24');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (34, 'University of British Columbia', '2');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (35, 'The University of Manchester', '5');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (36, 'University of North Carolina at Chapel Hill', '25');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (37, 'Rockefeller University', '26');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (38, 'University of Colorado at Boulder', '27');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (39, 'Pierre and Marie Curie University - Paris 6', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (40, 'The University of Melbourne', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (41, 'The University of Edinburgh', '6');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (42, 'University of California, Santa Barbara', '28');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (43, 'The University of Texas Southwestern Medical Center at Dallas', '29');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (44, 'Karolinska Institute', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (45, 'The University of Texas at Austin', '30');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (46, 'University of Paris-Sud (Paris 11)', '2');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (47, 'Heidelberg University', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (48, 'Technical University Munich', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (49, 'University of Southern California', '31');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (50, 'Kings College London', '7');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (51, 'University of Munich', '3');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (52, 'University of Maryland, College Park', '32');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (53, 'University of Geneva', '2');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (54, 'University of Zurich', '3');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (55, 'The University of Queensland', '2');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (56, 'University of Helsinki', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (57, 'University of Bristol', '8');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (58, 'Tsinghua University', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (59, 'University of California, Irvine', '33');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (60, 'Uppsala University', '2');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (61, 'Vanderbilt University', '34');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (62, 'Ghent University', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (63, 'McGill University', '3');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (64, 'Purdue University - West Lafayette', '35');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (65, 'Aarhus University', '2');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (66, 'Utrecht University', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (67, 'University of Oslo', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (68, 'Carnegie Mellon University', '36');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (69, 'Technion-Israel Institute of Technology', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (70, 'University of Pittsburgh, Pittsburgh Campus', '37');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (71, 'Peking University', '2');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (72, 'Nagoya University', '3');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (73, 'Rice University', '38');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (74, 'University of Groningen', '2');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (75, 'Boston University', '39');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (76, 'University of California, Davis', '39');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (77, 'Pennsylvania State University - University Park', '41');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (78, 'The Australian National University', '3');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (79, 'Monash University', '4');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (80, 'The Ohio State University - Columbus', '42');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (81, 'Stockholm University', '3');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (82, 'University of Sydney', '5');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (83, 'McMaster University', '4');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (84, 'National University of Singapore', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (85, 'University of California, Santa Cruz', '43');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (86, 'Mayo Medical School', '44');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (87, 'Ecole Normale Superieure - Paris', '3');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (88, 'Moscow State University', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (89, 'The Hebrew University of Jerusalem', '2');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (90, 'Brown University', '45');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (91, 'University of Florida', '45');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (92, 'Swiss Federal Institute of Technology Lausanne', '4');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (93, 'Georgia Institute of Technology', '47');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (94, 'KU Leuven', '2');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (95, 'Leiden University', '3');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (96, 'Osaka University', '4');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (97, 'Rutgers, The State University of New Jersey - New Brunswick', '48');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (98, 'The University of Texas M. D. Anderson Cancer Center', '48');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (99, 'The University of Western Australia', '6');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (100, 'University of Utah', '50');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (101, 'Aix Marseille University', '42890');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (102, 'Arizona State University', '51-61');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (103, 'Baylor College of Medicine', '51-61');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (104, 'Cardiff University', '42248');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (105, 'Case Western Reserve University', '51-61');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (106, 'Emory University', '51-61');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (107, 'Erasmus University', '42951');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (108, 'Fudan University', '42889');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (109, 'Icahn School of Medicine at Mount Sinai', '51-61');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (110, 'Indiana University Bloomington', '51-61');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (111, 'King Abdulaziz University', '42767');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (112, 'King Saud University', '42767');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (113, 'Lund University', '4');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (114, 'Michigan State University', '51-61');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (115, 'Nanyang Technological University', '2');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (116, 'Norwegian University of Science and Technology - NTNU', '2');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (117, 'Radboud University Nijmegen', '42951');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (118, 'Seoul National University', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (119, 'Shanghai Jiao Tong University', '42889');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (120, 'Texas A&M University', '51-61');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (121, 'The University of Adelaide', '42954');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (122, 'The University of Hong Kong', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (123, 'The University of New South Wales', '42954');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (124, 'The University of Sheffield', '42248');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (125, 'Tohoku University', '5');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (126, 'Tufts University', '51-61');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (127, 'University of Alberta', '5');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (128, 'University of Amsterdam', '42951');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (129, 'University of Arizona', '51-61');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (130, 'University of Basel', '42891');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (131, 'University of Bern', '42891');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (132, 'University of Birmingham', '42248');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (133, 'University of Bonn', '42951');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (134, 'University of Frankfurt', '42951');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (135, 'University of Freiburg', '42951');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (136, 'University of Goettingen', '42951');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (137, 'University of Leeds', '42248');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (138, 'University of Liverpool', '42248');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (139, 'University of Muenster', '42951');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (140, 'University of Nottingham', '42248');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (141, 'University of Rochester', '51-61');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (142, 'University of Sao Paulo', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (143, 'University of Science and Technology of China', '42889');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (144, 'University of Southampton', '42248');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (145, 'University of Strasbourg', '42890');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (146, 'University of Wageningen', '42951');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (147, 'University Paris Diderot - Paris 7', '42890');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (148, 'VU University Amsterdam', '42951');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (149, 'Weizmann Institute of Science', '3');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (150, 'Zhejiang University', '42889');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (151, 'Catholic University of Louvain', '42828');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (152, 'China Medical University', '42767');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (153, 'Delft University of Technology', '9');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (154, 'Harbin Institute of Technology', '42985');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (155, 'Hokkaido University', '6');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (156, 'Joseph Fourier University (Grenoble 1)', '42985');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (157, 'Korea University', '42796');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (158, 'London School of Economics and Political Science', '16-21');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (159, 'London School of Hygiene & Tropical Medicine', '16-21');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (160, 'National Autonomous University of Mexico', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (161, 'National Taiwan University', '42767');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (162, 'Oregon Health and Science University', '62-71');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (163, 'Oregon State University', '62-71');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (164, 'Queen Mary University of London', '16-21');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (165, 'Sapienza University of Rome', '42767');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (166, 'Sun Yat-sen University', '42985');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (167, 'Sungkyunkwan University', '42796');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (168, 'Technical University of Denmark', '3');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (169, 'Tel Aviv University', '4');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (170, 'The University of Auckland', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (171, 'The University of Glasgow', '16-21');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (172, 'Trinity College Dublin', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (173, 'TU Dresden', '41883');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (174, 'Université libre de Bruxelles (ULB)', '42828');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (175, 'University of Barcelona', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (176, 'University of Bordeaux', '42985');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (177, 'University of Buenos Aires', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (178, 'University of California, Riverside', '62-71');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (179, 'University of Delaware', '62-71');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (180, 'University of Erlangen-Nuremberg', '41883');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (181, 'University of Exeter', '16-21');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (182, 'University of Gothenburg', '5');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (183, 'University of Hawaii at Manoa', '62-71');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (184, 'University of Innsbruck', '42767');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (185, 'University of Iowa', '62-71');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (186, 'University of Kiel', '41883');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (187, 'University of Leipzig', '41883');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (188, 'University of Lisbon', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (189, 'University of Massachusetts Amherst', '62-71');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (190, 'University of Massachusetts Medical School - Worcester', '62-71');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (191, 'University of Miami', '62-71');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (192, 'University of Montreal', '6');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (193, 'University of Padua', '42767');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (194, 'University of Paris Descartes (Paris 5)', '42985');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (195, 'University of Tuebingen', '41883');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (196, 'University of Vienna', '42767');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (197, 'University of Virginia', '62-71');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (198, 'University of Warwick', '16-21');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (199, 'University of Wuerzburg', '41883');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (200, 'Xian Jiao Tong University', '42985');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (201, 'Aalborg University', '4');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (202, 'Autonomous University of Madrid', '42796');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (203, 'Beijing Normal University', '43374');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (204, 'Brandeis University', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (205, 'Chalmers University of Technology', '42953');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (206, 'Charles University in Prague', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (207, 'City University of Hong Kong', '42827');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (208, 'Claude Bernard University Lyon 1', '41548');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (209, 'Colorado State University', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (210, 'Curtin University', '41883');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (211, 'Dartmouth College', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (212, 'Deakin University', '41883');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (213, 'Drexel University', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (214, 'Durham University', '22-28');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (215, 'Eindhoven University of Technology', '43049');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (216, 'Florida State University', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (217, 'George Mason University', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (218, 'Huazhong University of Science and Technology', '43374');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (219, 'Indiana University-Purdue University at Indianapolis', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (220, 'Iowa State University', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (221, 'James Cook University', '41883');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (222, 'Jilin University', '43374');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (223, 'Karlsruhe Institute of Technology (KIT)', '15-21');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (224, 'King Abdullah University of Science and Technology', '3');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (225, 'Korea Advanced Institute of Science and Technology', '42890');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (226, 'KTH Royal Institute of Technology', '42953');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (227, 'Kyushu University', '42985');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (228, 'Laval University', '41456');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (229, 'Maastricht University', '43049');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (230, 'Macquarie University', '41883');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (231, 'Medical University of South Carolina', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (232, 'Medical University of Vienna', '3');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (233, 'Nanjing University', '43374');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (234, 'North Carolina State University - Raleigh', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (235, 'Northeastern University', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (236, 'Paul Sabatier University (Toulouse 3)', '41548');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (237, 'Pohang University of Science and Technology', '42890');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (238, 'Polytechnic Institute of Milan', '42950');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (239, 'Queens University', '41456');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (240, 'Queensland University of Technology', '41883');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (241, 'RWTH Aachen University', '15-21');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (242, 'Sichuan University', '43374');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (243, 'Soochow University', '43374');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (244, 'South China University of Technology', '43374');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (245, 'Southeast University', '43374');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (246, 'Stony Brook University', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (247, 'Swedish University of Agricultural Sciences', '42953');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (248, 'The Chinese University of Hong Kong', '42827');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (249, 'The Hong Kong University of Science and Technology', '42827');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (250, 'The University of Calgary', '41456');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (251, 'The University of Dundee', '22-28');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (252, 'The University of Georgia', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (253, 'The University of New Mexico - Albuquerque', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (254, 'The University of Texas Health Science Center at Houston', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (255, 'Tokyo Institute of Technology', '42985');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (256, 'Toulouse School of Economics', '41548');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (257, 'University of Aberdeen', '22-28');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (258, 'University of Alabama at Birmingham', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (259, 'University of Antwerp', '42891');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (260, 'University of Belgrade', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (261, 'University of Bergen', '3');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (262, 'University of Bochum', '15-21');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (263, 'University of Bologna', '42950');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (264, 'University of Cape Town', '42767');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (265, 'University of Cincinnati', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (266, 'University of East Anglia', '22-28');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (267, 'University of Florence', '42950');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (268, 'University of Granada', '42796');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (269, 'University of Hamburg', '15-21');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (270, 'University of Houston', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (271, 'University of Illinois at Chicago', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (272, 'University of Kansas', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (273, 'University of Koeln', '15-21');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (274, 'University of Lausanne', '7');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (275, 'University of Leicester', '22-28');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (276, 'University of Lorraine', '41548');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (277, 'University of Mainz', '15-21');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (278, 'University of Maryland, Baltimore', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (279, 'University of Milan', '42950');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (280, 'University of Missouri - Columbia', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (281, 'University of Nebraska - Lincoln', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (282, 'University of Notre Dame', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (283, 'University of Ottawa', '41456');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (284, 'University of Pisa', '42950');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (285, 'University of South Florida', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (286, 'University of Sussex', '22-28');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (287, 'University of Tasmania', '41883');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (288, 'University of the Witwatersrand', '42767');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (289, 'University of Tsukuba', '42985');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (290, 'University of Turin', '42950');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (291, 'University of Ulm', '15-21');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (292, 'University of Victoria', '41456');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (293, 'University of Waterloo', '41456');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (294, 'University of York', '22-28');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (295, 'Virginia Commonwealth University', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (296, 'Vrije Universiteit Brussel (VUB)', '42891');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (297, 'Western University', '41456');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (298, 'Xiamen University', '43374');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (299, 'Yeshiva University', '72-98');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (300, 'Yonsei University', '42890');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (301, 'Autonomous University of Barcelona', '42982');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (302, 'Beihang University', '19-31');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (303, 'Boston College', '99-119');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (304, 'Catholic University of Korea', '42985');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (305, 'Central South University', '19-31');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (306, 'Chang Gung University', '42828');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (307, 'Chiba University', '43079');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (308, 'China Agricultural University', '19-31');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (309, 'China University of Geosciences (Wuhan)', '19-31');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (310, 'Complutense University of Madrid', '42982');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (311, 'Dalhousie University', '14-16');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (312, 'Dalian University of Technology', '19-31');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (313, 'East China University of Science and Technology', '19-31');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (314, 'Ecole Normale Superieure - Lyon', '14-18');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (315, 'Ecole Polytechnique', '14-18');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (316, 'ESPCI ParisTech', '14-18');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (317, 'Federal University of Minas Gerais', '42827');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (318, 'Federal University of Rio de Janeiro', '42827');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (319, 'Flinders University', '15-21');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (320, 'Georgetown University', '99-119');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (321, 'Griffith University', '15-21');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (322, 'Hannover Medical School', '22-27');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (323, 'Hanyang University', '42985');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (324, 'Indian Institute of Science', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (325, 'Keio University', '43079');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (326, 'King Fahd University of Petroleum & Minerals', '4');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (327, 'Kyung Hee University', '42985');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (328, 'La Trobe University', '15-21');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (329, 'Lanzhou University', '19-31');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (330, 'Linkoping University', '43017');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (331, 'Louisiana State University - Baton Rouge', '99-119');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (332, 'Nankai University', '19-31');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (333, 'National and Kapodistrian University of Athens', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (334, 'National Tsing Hua University', '42828');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (335, 'National University of Ireland, Galway', '42796');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (336, 'Newcastle University', '29-33');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (337, 'Okayama University', '43079');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (338, 'Paris Dauphine University (Paris 9)', '14-18');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (339, 'Polytechnic University of Catalonia', '42982');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (340, 'Polytechnic University of Valencia', '42982');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (341, 'Pompeu Fabra University', '42982');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (342, 'Queens University Belfast', '29-33');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (343, 'Rush University', '99-119');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (344, 'Saint Petersburg State University', '2');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (345, 'Shandong University', '19-31');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (346, 'Technical University of Berlin', '22-27');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (347, 'Temple University', '99-119');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (348, 'The George Washington University', '99-119');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (349, 'The Hong Kong Polytechnic University', '5');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (350, 'The University of Newcastle, Australia', '15-21');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (351, 'The University of Reading', '29-33');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (352, 'The University of Texas at Dallas', '99-119');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (353, 'The University of Texas Health Science Center at San Antonio', '99-119');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (354, 'Thomas Jefferson University', '99-119');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (355, 'Tianjin University', '19-31');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (356, 'Tongji University', '19-31');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (357, 'Umea University', '43017');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (358, 'UNESP', '42827');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (359, 'University at Buffalo, the State University of New York', '99-119');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (360, 'University College Dublin', '42796');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (361, 'University of Bath', '29-33');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (362, 'University of Canterbury', '42827');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (363, 'University of Chile', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (364, 'University of Colorado at Denver', '99-119');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (365, 'University of Connecticut', '99-119');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (366, 'University of Eastern Finland', '2');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (367, 'University of Electronic Science and Technology of China', '19-31');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (368, 'University of Fribourg', '8');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (369, 'University of Giessen', '22-27');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (370, 'University of Guelph', '14-16');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (371, 'University of Halle-Wittenberg', '22-27');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (372, 'University of Jena', '22-27');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (373, 'University of Kentucky', '99-119');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (374, 'University of Liege', '7');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (375, 'University of Marburg', '22-27');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (376, 'University of Maryland, Baltimore County', '99-119');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (377, 'University of Milan - Bicocca', '43048');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (378, 'University of Montpellier', '14-18');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (379, 'University of Naples Federico II', '43048');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (380, 'University of North Texas', '99-119');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (381, 'University of Oregon', '99-119');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (382, 'University of Otago', '42827');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (383, 'University of Pavia', '43048');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (384, 'University of Porto', '2');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (385, 'University of Quebec', '14-16');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (386, 'University of Santiago Compostela', '42982');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (387, 'University of South Carolina - Columbia', '99-119');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (388, 'University of Southern Denmark', '5');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (389, 'University of St Andrews', '29-33');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (390, 'University of Technology, Sydney', '15-21');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (391, 'University of Tehran', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (392, 'University of Tennessee - Knoxville', '99-119');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (393, 'University of Twente', '12');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (394, 'University of Vermont', '99-119');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (395, 'University of Western Sydney', '15-21');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (396, 'University of Wollongong', '15-21');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (397, 'Victoria University of Wellington', '42827');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (398, 'Virginia Polytechnic Institute and State University', '99-119');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (399, 'Wayne State University', '99-119');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (400, 'Wuhan University', '19-31');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (401, 'Aalto University', '42858');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (402, 'Amirkabir University of Technology', '2');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (403, 'Aristotle University of Thessaloniki', '2');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (404, 'Bangor University', '34-37');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (405, 'Beijing University of Chemical Technology', '32-41');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (406, 'Ben-Gurion University of the Negev', '5');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (407, 'Bielefeld University', '28-38');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (408, 'Brigham Young University', '120-137');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (409, 'Brunel University', '34-37');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (410, 'Cairo University', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (411, 'Capital Medical University', '32-41');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (412, 'City University of New York City College', '120-137');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (413, 'Donghua University', '32-41');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (414, 'Ewha Womans University', '43049');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (415, 'Federal University of Rio Grande do Sul', '42891');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (416, 'Florida International University', '120-137');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (417, 'Hong Kong Baptist University', '6');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (418, 'Hunan University', '32-41');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (419, 'Istanbul University', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (420, 'Jagiellonian University', '42767');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (421, 'Kaohsiung Medical University', '42921');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (422, 'Kobe University', '13-16');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (423, 'Medical University of Graz', '42859');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (424, 'MINES ParisTech', '19-22');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (425, 'Nanjing Medical University', '32-41');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (426, 'Nanjing University of Science and Technology', '32-41');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (427, 'National Cheng Kung University (NCKU)', '42921');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (428, 'National Chiao Tung University', '42921');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (429, 'National University of Malaysia', '42795');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (430, 'Northeast Normal University', '32-41');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (431, 'Novosibirsk State University', '3');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (432, 'Ocean University of China', '32-41');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (433, 'Oklahoma State University', '120-137');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (434, 'Osaka City University', '13-16');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (435, 'Paris Sorbonne University', '19-22');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (436, 'Peking Union Medical College', '32-41');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (437, 'Pusan National University', '43049');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (438, 'Rensselaer Polytechnic Institute', '120-137');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (439, 'RMIT University', '22-23');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (440, 'Saint Louis University', '120-137');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (441, 'San Diego State University', '120-137');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (442, 'Scuola Normale Superiore - Pisa', '43800');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (443, 'Simon Fraser University', '17-19');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (444, 'St Georges Hospital Medical School', '34-37');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (445, 'Stellenbosch University', '42828');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (446, 'Stockholm School of Economics', '11');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (447, 'Swinburne University of Technology', '22-23');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (448, 'Technical University Darmstadt', '28-38');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (449, 'Texas Tech University', '120-137');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (450, 'The University of Texas Medical Branch at Galveston', '120-137');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (451, 'Tokyo University of Science', '13-16');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (452, 'University at Albany (State University of New York)', '120-137');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (453, 'University of Alaska - Fairbanks', '120-137');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (454, 'University of Aveiro', '42858');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (455, 'University of Bayreuth', '28-38');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (456, 'University of Bremen', '28-38');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (457, 'University of Campinas', '42891');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (458, 'University of Central Florida', '120-137');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (459, 'University of Coimbra', '42858');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (460, 'University of Duesseldorf', '28-38');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (461, 'University of Ferrara', '43800');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (462, 'University of Hannover', '28-38');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (463, 'University of Konstanz', '28-38');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (464, 'University of KwaZulu-Natal', '42828');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (465, 'University of Ljubljana', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (466, 'University of Malaya', '42795');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (467, 'University of Manitoba', '17-19');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (468, 'University of Minho', '42858');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (469, 'University of Montana - Missoula', '120-137');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (470, 'University of Nice Sophia Antipolis', '19-22');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (471, 'University of Oulu', '42858');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (472, 'University of Palermo', '43800');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (473, 'University of Parma', '43800');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (474, 'University of Perugia', '43800');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (475, 'University of Potsdam', '28-38');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (476, 'University of Regensburg', '28-38');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (477, 'University of Roma - Tor Vergata', '43800');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (478, 'University of Rostock', '28-38');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (479, 'University of Salerno', '43800');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (480, 'University of Saskatchewan', '17-19');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (481, 'University of Science, Malaysia', '42795');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (482, 'University of Stuttgart', '28-38');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (483, 'University of Surrey', '34-37');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (484, 'University of Tartu', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (485, 'University of the Basque Country', '43079');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (486, 'University of Turku', '42858');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (487, 'University of Valencia', '43079');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (488, 'University of Versailles Saint-Quentin-en-Yvelines', '19-22');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (489, 'University of Warsaw', '42767');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (490, 'University of Wyoming', '120-137');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (491, 'University of Zagreb', '1');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (492, 'University Rovira i Virgili', '43079');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (493, 'Utah State University', '120-137');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (494, 'Vienna University of Technology', '42859');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (495, 'Vita-Salute San Raffaele University', '43800');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (496, 'Wake Forest University', '120-137');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (497, 'Waseda University', '13-16');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (498, 'Washington State University', '120-137');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (499, 'West Virginia University', '120-137');
INSERT INTO Universities (WorldRank, Institution, NationalRank) VALUES (500, 'Wuhan University of Technology', '32-41');
